// Generated by CoffeeScript 1.9.2
(function() {
  var exec;

  exec = require('child_process').exec;

  module.exports = function(path, opts, cb) {
    return exec("find " + path + " " + opts, {
      maxBuffer: 1024 * 1024 * 1024
    }, function(e, stdout, stderr) {
      var fileName, fileNames, i, len, paths, ref;
      if (e != null) {
        return cb([e, stderr], []);
      }
      fileNames = [];
      paths = [];
      ref = stdout.split('\n').slice(0, -1);
      for (i = 0, len = ref.length; i < len; i++) {
        path = ref[i];
        fileName = path.split('/').pop();
        fileNames.push(fileName);
        paths.push(path);
      }
      return cb(null, fileNames, paths);
    });
  };

}).call(this);
